### ISSUE TITLE
关于step文件中的运行报错的问题

### ISSUE THREAD

**Issue by LoyeEumenides** [zhaoxuhui/NBNet-Demo#1]
首先，十分感谢作者提供了一种便捷，系统的使用NB-Net的流程。但是本人初学python以及深度学习，出现了一些问题，还望作者不吝赐教。
我按您在博客上的流程，下载了您网盘中提供的三张图片，设置了.yml参数文件里的参数，将对应的各个文件路径修改为自己的绝对路径。运行step1、step2、step3，均发现如下类似报错：

Traceback (most recent call last):
  File "E:/NBNet-Demo-main/Scripts/step1_training_gen_blocks.py", line 7, in <module>
    raw_dir = sys.argv[1]  # raw影像所在路径
IndexError: list index out of range
（此为step1_training_gen_blocks.py的报错）

本人有如下问题及分析：
1. 搜索了一下sys.argv[]的用法，发现这是一个从程序外部传入参数的函数，但本人初学，实在没分析出问题在哪
2. 本人系统为Windows系统，是否是因为在.yml文件输入的路径中"/"和"\"的问题（但是试过了"/", "\", "\\"都还是不能正常运行）
3. 在运行steps_training.py时，没有报错，返回了如下值
python3 step1_training_gen_blocks.py    CR3 CR3 png 256 500 0.1 raw rgb
python3 step2_training_gen_vali_mat.py /validation/input /validation/groundtruth png png /validation
python3 step3_training_start.py    50 200 32
但是没有出现.pkl文件

因本人水平有限，无法全部读懂并分析作者的代码，遂发表评论说明问题。也是首次在github上发表评论，如有冒犯还请指正，感激不尽！

**Comment by zhaoxuhui** [comment]
你好，感谢提问！最近有点忙，所以回复有点晚。
我在我的电脑上试着运行了一下你说的step1_training_gen_blocks.py，是可以正常运行的，输出如下：

  C:\Users\admin\Desktop\NBNet-Demo-main\NBNet-Demo-main\Scripts> python .\step1_training_gen_blocks.py C:\Users\admin\Desktop\NBNet-Demo-main\NBNet-Demo-main\Datasets\input C:\Users\admin\Desktop\NBNet-Demo-main\NBNet-Demo-main\Datasets\gt C:\Users\admin\Desktop\NBNet-Demo-main\NBNet-Demo-main\Datasets\input_blocks .CR3 .CR3 .png 512 100 0.3
  Finding files ends with '.CR3' ...
  1 files have been found.
  Finding files ends with '.CR3' ...
  1 files have been found.
  processing 1 / 1 ......
  raw
  raw
  Added 50 / 100
  Added 100 / 100
  Enhanced 50 / 100
  Enhanced 100 / 100
  Saved train03.CR3 : 50 / 400
  Saved train03.CR3 : 100 / 400
  Saved train03.CR3 : 150 / 400
  Saved train03.CR3 : 200 / 400
  Saved train03.CR3 : 250 / 400
  Saved train03.CR3 : 300 / 400
  Saved train03.CR3 : 350 / 400
  Saved train03.CR3 : 400 / 400

所以你运行有问题十有八九还是输入的参数没给对。简单说明一下脚本启动的9个参数：

    raw_dir = sys.argv[1]  # raw影像所在路径，比如C:\Images
    gt_dir = sys.argv[2]  # gt影像所在路径，比如C:\GT_images
    out_dir = sys.argv[3]  # 影像块输出路径，比如C:\Image_blocks

    raw_type = sys.argv[4]  # raw文件格式，比如.CR3
    gt_type = sys.argv[5]  # gt文件格式，比如.CR3
    out_type = sys.argv[6]  # 输出影像块格式，比如.png

    block_size = int(sys.argv[7])  # 影像块大小，比如512
    num_sample = int(sys.argv[8])  # 影像块个数，比如100
    validation_rate = float(sys.argv[9])  # 验证块个数占比，比如0.3

所以你可以对照着上面的说明看看哪个参数输入的不对。如果还有疑问，欢迎继续提问~

**Comment by LoyeEumenides** [comment]
感谢您详细的指点，对我很有帮助！
